fix(static-analysis): unpausing and refractoring semgrep checks
open-turo/actions-security pull request #37
Opened 2024-11-22 23:14 UTC by pkanoongo

**Description**

The PR restructures the repo to move the semgrep workflow action from '/static-analysis/semgrep' to '/static-analysis'. All the references to the semgrep are updated to use the new path. Also, unpausing the semgrep checks.

**Fixes**

- fix(static-analysis):restructuring the repos.
- fix(static-analysis): test unpausing semgrep checks

2024-11-22 23:22 UTC, prathamesh16c requested changes
can you update the path on the test file too

2024-11-22 23:42 UTC, pkanoongo commented
Update the path on test. Both checks have passed. Thanks!!

2024-11-25 18:44 UTC, pkanoongo reviewed
Fixed the path.

2024-11-25 18:44 UTC, pkanoongo commented on .github/workflows/ci.yaml
> +      - uses: ./static-analysis
Updated the path here.

2024-11-27 01:20 UTC, prathamesh16c requested changes
@pkanoongo please can you create a retroactive breaking change doc in this repo and add instructions for the consuming repos on using the refactored path of this action.

2024-11-27 18:24 UTC, pkanoongo commented on static-analysis/action.yaml
I think option2 is better. We will add instructions in our breaking change doc.

2024-12-18 17:29 UTC, pkanoongo commented
Cleanup:
This is no longer required. Closing the PR.

2024-12-18 17:29 UTC, closed without merging