fix(static-analysis): fixing diff aware scanning for semgrep
open-turo/actions-security pull request #45
Opened 2024-12-10 19:05 UTC by pkanoongo

Description:-

During the testing, we identified that the semgrep is not running the diff aware scans instead it is currently scanning the entire repo. As per the semgrep diff aware [documentation](https://semgrep.dev/docs/kb/semgrep-ci/trigger-diff-scans-env-var), our current setup might be failing because the diff-aware scanning requires a baseline reference to compare against the branch head. As the part of this fix,  we are dynamically determining the baseline branch for each repository for semgrep to compare. Creating this branch to test and confirm the fix. 

Fixes:-
/static-analysis/semgrep/action.yaml.

2024-12-10 20:42 UTC, pkanoongo commented
No need to review or approve. Testing the fix on this branch.

2024-12-16 23:04 UTC, prathamesh16c requested changes
Small updates - 
- Please can we squash all commits into one 
- make this a `feat` since we are resuming checks again.

2024-12-17 19:04 UTC, pkanoongo commented
All previous commits are squashed.

2024-12-17 19:06 UTC, prathamesh16c approved these changes

2024-12-17 19:06 UTC, prathamesh16c approved these changes

2024-12-17 19:07 UTC, tagoro9 approved these changes

2024-12-17 19:07 UTC, merged